// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mutation_Proto.proto

package com._42six.amino.common.bigtable;

public final class MutationProto {
  private MutationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ColumnValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes column_family = 1;
    /**
     * <code>required bytes column_family = 1;</code>
     */
    boolean hasColumnFamily();
    /**
     * <code>required bytes column_family = 1;</code>
     */
    com.google.protobuf.ByteString getColumnFamily();

    // required bytes column_qualifier = 2;
    /**
     * <code>required bytes column_qualifier = 2;</code>
     */
    boolean hasColumnQualifier();
    /**
     * <code>required bytes column_qualifier = 2;</code>
     */
    com.google.protobuf.ByteString getColumnQualifier();

    // required bytes column_visibility = 3;
    /**
     * <code>required bytes column_visibility = 3;</code>
     */
    boolean hasColumnVisibility();
    /**
     * <code>required bytes column_visibility = 3;</code>
     */
    com.google.protobuf.ByteString getColumnVisibility();

    // required uint64 timestamp = 4;
    /**
     * <code>required uint64 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 4;</code>
     */
    long getTimestamp();

    // required bool isDelete = 5;
    /**
     * <code>required bool isDelete = 5;</code>
     */
    boolean hasIsDelete();
    /**
     * <code>required bool isDelete = 5;</code>
     */
    boolean getIsDelete();

    // optional bytes value = 6;
    /**
     * <code>optional bytes value = 6;</code>
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 6;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code com._42six.amino.common.bigtable.ColumnValue}
   */
  public static final class ColumnValue extends
      com.google.protobuf.GeneratedMessage
      implements ColumnValueOrBuilder {
    // Use ColumnValue.newBuilder() to construct.
    private ColumnValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ColumnValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ColumnValue defaultInstance;
    public static ColumnValue getDefaultInstance() {
      return defaultInstance;
    }

    public ColumnValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ColumnValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              columnFamily_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              columnQualifier_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              columnVisibility_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              isDelete_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_ColumnValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_ColumnValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com._42six.amino.common.bigtable.MutationProto.ColumnValue.class, com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder.class);
    }

    public static com.google.protobuf.Parser<ColumnValue> PARSER =
        new com.google.protobuf.AbstractParser<ColumnValue>() {
      public ColumnValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ColumnValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ColumnValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes column_family = 1;
    public static final int COLUMN_FAMILY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString columnFamily_;
    /**
     * <code>required bytes column_family = 1;</code>
     */
    public boolean hasColumnFamily() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes column_family = 1;</code>
     */
    public com.google.protobuf.ByteString getColumnFamily() {
      return columnFamily_;
    }

    // required bytes column_qualifier = 2;
    public static final int COLUMN_QUALIFIER_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString columnQualifier_;
    /**
     * <code>required bytes column_qualifier = 2;</code>
     */
    public boolean hasColumnQualifier() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes column_qualifier = 2;</code>
     */
    public com.google.protobuf.ByteString getColumnQualifier() {
      return columnQualifier_;
    }

    // required bytes column_visibility = 3;
    public static final int COLUMN_VISIBILITY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString columnVisibility_;
    /**
     * <code>required bytes column_visibility = 3;</code>
     */
    public boolean hasColumnVisibility() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes column_visibility = 3;</code>
     */
    public com.google.protobuf.ByteString getColumnVisibility() {
      return columnVisibility_;
    }

    // required uint64 timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // required bool isDelete = 5;
    public static final int ISDELETE_FIELD_NUMBER = 5;
    private boolean isDelete_;
    /**
     * <code>required bool isDelete = 5;</code>
     */
    public boolean hasIsDelete() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool isDelete = 5;</code>
     */
    public boolean getIsDelete() {
      return isDelete_;
    }

    // optional bytes value = 6;
    public static final int VALUE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>optional bytes value = 6;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes value = 6;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private void initFields() {
      columnFamily_ = com.google.protobuf.ByteString.EMPTY;
      columnQualifier_ = com.google.protobuf.ByteString.EMPTY;
      columnVisibility_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      isDelete_ = false;
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasColumnFamily()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumnQualifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumnVisibility()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsDelete()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, columnFamily_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, columnQualifier_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, columnVisibility_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, isDelete_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, columnFamily_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, columnQualifier_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, columnVisibility_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isDelete_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com._42six.amino.common.bigtable.MutationProto.ColumnValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com._42six.amino.common.bigtable.MutationProto.ColumnValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com._42six.amino.common.bigtable.ColumnValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_ColumnValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_ColumnValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com._42six.amino.common.bigtable.MutationProto.ColumnValue.class, com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder.class);
      }

      // Construct using com._42six.amino.common.bigtable.MutationProto.ColumnValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        columnFamily_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        columnQualifier_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        columnVisibility_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        isDelete_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_ColumnValue_descriptor;
      }

      public com._42six.amino.common.bigtable.MutationProto.ColumnValue getDefaultInstanceForType() {
        return com._42six.amino.common.bigtable.MutationProto.ColumnValue.getDefaultInstance();
      }

      public com._42six.amino.common.bigtable.MutationProto.ColumnValue build() {
        com._42six.amino.common.bigtable.MutationProto.ColumnValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com._42six.amino.common.bigtable.MutationProto.ColumnValue buildPartial() {
        com._42six.amino.common.bigtable.MutationProto.ColumnValue result = new com._42six.amino.common.bigtable.MutationProto.ColumnValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.columnFamily_ = columnFamily_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.columnQualifier_ = columnQualifier_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.columnVisibility_ = columnVisibility_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isDelete_ = isDelete_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com._42six.amino.common.bigtable.MutationProto.ColumnValue) {
          return mergeFrom((com._42six.amino.common.bigtable.MutationProto.ColumnValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com._42six.amino.common.bigtable.MutationProto.ColumnValue other) {
        if (other == com._42six.amino.common.bigtable.MutationProto.ColumnValue.getDefaultInstance()) return this;
        if (other.hasColumnFamily()) {
          setColumnFamily(other.getColumnFamily());
        }
        if (other.hasColumnQualifier()) {
          setColumnQualifier(other.getColumnQualifier());
        }
        if (other.hasColumnVisibility()) {
          setColumnVisibility(other.getColumnVisibility());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasIsDelete()) {
          setIsDelete(other.getIsDelete());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasColumnFamily()) {
          
          return false;
        }
        if (!hasColumnQualifier()) {
          
          return false;
        }
        if (!hasColumnVisibility()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasIsDelete()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com._42six.amino.common.bigtable.MutationProto.ColumnValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com._42six.amino.common.bigtable.MutationProto.ColumnValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes column_family = 1;
      private com.google.protobuf.ByteString columnFamily_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes column_family = 1;</code>
       */
      public boolean hasColumnFamily() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes column_family = 1;</code>
       */
      public com.google.protobuf.ByteString getColumnFamily() {
        return columnFamily_;
      }
      /**
       * <code>required bytes column_family = 1;</code>
       */
      public Builder setColumnFamily(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        columnFamily_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes column_family = 1;</code>
       */
      public Builder clearColumnFamily() {
        bitField0_ = (bitField0_ & ~0x00000001);
        columnFamily_ = getDefaultInstance().getColumnFamily();
        onChanged();
        return this;
      }

      // required bytes column_qualifier = 2;
      private com.google.protobuf.ByteString columnQualifier_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes column_qualifier = 2;</code>
       */
      public boolean hasColumnQualifier() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes column_qualifier = 2;</code>
       */
      public com.google.protobuf.ByteString getColumnQualifier() {
        return columnQualifier_;
      }
      /**
       * <code>required bytes column_qualifier = 2;</code>
       */
      public Builder setColumnQualifier(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        columnQualifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes column_qualifier = 2;</code>
       */
      public Builder clearColumnQualifier() {
        bitField0_ = (bitField0_ & ~0x00000002);
        columnQualifier_ = getDefaultInstance().getColumnQualifier();
        onChanged();
        return this;
      }

      // required bytes column_visibility = 3;
      private com.google.protobuf.ByteString columnVisibility_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes column_visibility = 3;</code>
       */
      public boolean hasColumnVisibility() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes column_visibility = 3;</code>
       */
      public com.google.protobuf.ByteString getColumnVisibility() {
        return columnVisibility_;
      }
      /**
       * <code>required bytes column_visibility = 3;</code>
       */
      public Builder setColumnVisibility(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        columnVisibility_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes column_visibility = 3;</code>
       */
      public Builder clearColumnVisibility() {
        bitField0_ = (bitField0_ & ~0x00000004);
        columnVisibility_ = getDefaultInstance().getColumnVisibility();
        onChanged();
        return this;
      }

      // required uint64 timestamp = 4;
      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // required bool isDelete = 5;
      private boolean isDelete_ ;
      /**
       * <code>required bool isDelete = 5;</code>
       */
      public boolean hasIsDelete() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool isDelete = 5;</code>
       */
      public boolean getIsDelete() {
        return isDelete_;
      }
      /**
       * <code>required bool isDelete = 5;</code>
       */
      public Builder setIsDelete(boolean value) {
        bitField0_ |= 0x00000010;
        isDelete_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isDelete = 5;</code>
       */
      public Builder clearIsDelete() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isDelete_ = false;
        onChanged();
        return this;
      }

      // optional bytes value = 6;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 6;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes value = 6;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 6;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value = 6;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com._42six.amino.common.bigtable.ColumnValue)
    }

    static {
      defaultInstance = new ColumnValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com._42six.amino.common.bigtable.ColumnValue)
  }

  public interface MutationCodecOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes row = 1;
    /**
     * <code>required bytes row = 1;</code>
     */
    boolean hasRow();
    /**
     * <code>required bytes row = 1;</code>
     */
    com.google.protobuf.ByteString getRow();

    // repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    java.util.List<com._42six.amino.common.bigtable.MutationProto.ColumnValue> 
        getColumnValuesList();
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    com._42six.amino.common.bigtable.MutationProto.ColumnValue getColumnValues(int index);
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    int getColumnValuesCount();
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    java.util.List<? extends com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder> 
        getColumnValuesOrBuilderList();
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder getColumnValuesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com._42six.amino.common.bigtable.MutationCodec}
   */
  public static final class MutationCodec extends
      com.google.protobuf.GeneratedMessage
      implements MutationCodecOrBuilder {
    // Use MutationCodec.newBuilder() to construct.
    private MutationCodec(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MutationCodec(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MutationCodec defaultInstance;
    public static MutationCodec getDefaultInstance() {
      return defaultInstance;
    }

    public MutationCodec getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MutationCodec(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              row_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                columnValues_ = new java.util.ArrayList<com._42six.amino.common.bigtable.MutationProto.ColumnValue>();
                mutable_bitField0_ |= 0x00000002;
              }
              columnValues_.add(input.readMessage(com._42six.amino.common.bigtable.MutationProto.ColumnValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          columnValues_ = java.util.Collections.unmodifiableList(columnValues_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_MutationCodec_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_MutationCodec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com._42six.amino.common.bigtable.MutationProto.MutationCodec.class, com._42six.amino.common.bigtable.MutationProto.MutationCodec.Builder.class);
    }

    public static com.google.protobuf.Parser<MutationCodec> PARSER =
        new com.google.protobuf.AbstractParser<MutationCodec>() {
      public MutationCodec parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MutationCodec(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MutationCodec> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes row = 1;
    public static final int ROW_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString row_;
    /**
     * <code>required bytes row = 1;</code>
     */
    public boolean hasRow() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes row = 1;</code>
     */
    public com.google.protobuf.ByteString getRow() {
      return row_;
    }

    // repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;
    public static final int COLUMNVALUES_FIELD_NUMBER = 2;
    private java.util.List<com._42six.amino.common.bigtable.MutationProto.ColumnValue> columnValues_;
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    public java.util.List<com._42six.amino.common.bigtable.MutationProto.ColumnValue> getColumnValuesList() {
      return columnValues_;
    }
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    public java.util.List<? extends com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder> 
        getColumnValuesOrBuilderList() {
      return columnValues_;
    }
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    public int getColumnValuesCount() {
      return columnValues_.size();
    }
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    public com._42six.amino.common.bigtable.MutationProto.ColumnValue getColumnValues(int index) {
      return columnValues_.get(index);
    }
    /**
     * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
     */
    public com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder getColumnValuesOrBuilder(
        int index) {
      return columnValues_.get(index);
    }

    private void initFields() {
      row_ = com.google.protobuf.ByteString.EMPTY;
      columnValues_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getColumnValuesCount(); i++) {
        if (!getColumnValues(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, row_);
      }
      for (int i = 0; i < columnValues_.size(); i++) {
        output.writeMessage(2, columnValues_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, row_);
      }
      for (int i = 0; i < columnValues_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, columnValues_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com._42six.amino.common.bigtable.MutationProto.MutationCodec parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com._42six.amino.common.bigtable.MutationProto.MutationCodec prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com._42six.amino.common.bigtable.MutationCodec}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com._42six.amino.common.bigtable.MutationProto.MutationCodecOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_MutationCodec_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_MutationCodec_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com._42six.amino.common.bigtable.MutationProto.MutationCodec.class, com._42six.amino.common.bigtable.MutationProto.MutationCodec.Builder.class);
      }

      // Construct using com._42six.amino.common.bigtable.MutationProto.MutationCodec.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getColumnValuesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        row_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (columnValuesBuilder_ == null) {
          columnValues_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          columnValuesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com._42six.amino.common.bigtable.MutationProto.internal_static_com__42six_amino_common_bigtable_MutationCodec_descriptor;
      }

      public com._42six.amino.common.bigtable.MutationProto.MutationCodec getDefaultInstanceForType() {
        return com._42six.amino.common.bigtable.MutationProto.MutationCodec.getDefaultInstance();
      }

      public com._42six.amino.common.bigtable.MutationProto.MutationCodec build() {
        com._42six.amino.common.bigtable.MutationProto.MutationCodec result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com._42six.amino.common.bigtable.MutationProto.MutationCodec buildPartial() {
        com._42six.amino.common.bigtable.MutationProto.MutationCodec result = new com._42six.amino.common.bigtable.MutationProto.MutationCodec(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.row_ = row_;
        if (columnValuesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            columnValues_ = java.util.Collections.unmodifiableList(columnValues_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.columnValues_ = columnValues_;
        } else {
          result.columnValues_ = columnValuesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com._42six.amino.common.bigtable.MutationProto.MutationCodec) {
          return mergeFrom((com._42six.amino.common.bigtable.MutationProto.MutationCodec)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com._42six.amino.common.bigtable.MutationProto.MutationCodec other) {
        if (other == com._42six.amino.common.bigtable.MutationProto.MutationCodec.getDefaultInstance()) return this;
        if (other.hasRow()) {
          setRow(other.getRow());
        }
        if (columnValuesBuilder_ == null) {
          if (!other.columnValues_.isEmpty()) {
            if (columnValues_.isEmpty()) {
              columnValues_ = other.columnValues_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureColumnValuesIsMutable();
              columnValues_.addAll(other.columnValues_);
            }
            onChanged();
          }
        } else {
          if (!other.columnValues_.isEmpty()) {
            if (columnValuesBuilder_.isEmpty()) {
              columnValuesBuilder_.dispose();
              columnValuesBuilder_ = null;
              columnValues_ = other.columnValues_;
              bitField0_ = (bitField0_ & ~0x00000002);
              columnValuesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getColumnValuesFieldBuilder() : null;
            } else {
              columnValuesBuilder_.addAllMessages(other.columnValues_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRow()) {
          
          return false;
        }
        for (int i = 0; i < getColumnValuesCount(); i++) {
          if (!getColumnValues(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com._42six.amino.common.bigtable.MutationProto.MutationCodec parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com._42six.amino.common.bigtable.MutationProto.MutationCodec) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes row = 1;
      private com.google.protobuf.ByteString row_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes row = 1;</code>
       */
      public boolean hasRow() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public com.google.protobuf.ByteString getRow() {
        return row_;
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public Builder setRow(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public Builder clearRow() {
        bitField0_ = (bitField0_ & ~0x00000001);
        row_ = getDefaultInstance().getRow();
        onChanged();
        return this;
      }

      // repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;
      private java.util.List<com._42six.amino.common.bigtable.MutationProto.ColumnValue> columnValues_ =
        java.util.Collections.emptyList();
      private void ensureColumnValuesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          columnValues_ = new java.util.ArrayList<com._42six.amino.common.bigtable.MutationProto.ColumnValue>(columnValues_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com._42six.amino.common.bigtable.MutationProto.ColumnValue, com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder, com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder> columnValuesBuilder_;

      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public java.util.List<com._42six.amino.common.bigtable.MutationProto.ColumnValue> getColumnValuesList() {
        if (columnValuesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(columnValues_);
        } else {
          return columnValuesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public int getColumnValuesCount() {
        if (columnValuesBuilder_ == null) {
          return columnValues_.size();
        } else {
          return columnValuesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public com._42six.amino.common.bigtable.MutationProto.ColumnValue getColumnValues(int index) {
        if (columnValuesBuilder_ == null) {
          return columnValues_.get(index);
        } else {
          return columnValuesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public Builder setColumnValues(
          int index, com._42six.amino.common.bigtable.MutationProto.ColumnValue value) {
        if (columnValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnValuesIsMutable();
          columnValues_.set(index, value);
          onChanged();
        } else {
          columnValuesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public Builder setColumnValues(
          int index, com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder builderForValue) {
        if (columnValuesBuilder_ == null) {
          ensureColumnValuesIsMutable();
          columnValues_.set(index, builderForValue.build());
          onChanged();
        } else {
          columnValuesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public Builder addColumnValues(com._42six.amino.common.bigtable.MutationProto.ColumnValue value) {
        if (columnValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnValuesIsMutable();
          columnValues_.add(value);
          onChanged();
        } else {
          columnValuesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public Builder addColumnValues(
          int index, com._42six.amino.common.bigtable.MutationProto.ColumnValue value) {
        if (columnValuesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnValuesIsMutable();
          columnValues_.add(index, value);
          onChanged();
        } else {
          columnValuesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public Builder addColumnValues(
          com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder builderForValue) {
        if (columnValuesBuilder_ == null) {
          ensureColumnValuesIsMutable();
          columnValues_.add(builderForValue.build());
          onChanged();
        } else {
          columnValuesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public Builder addColumnValues(
          int index, com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder builderForValue) {
        if (columnValuesBuilder_ == null) {
          ensureColumnValuesIsMutable();
          columnValues_.add(index, builderForValue.build());
          onChanged();
        } else {
          columnValuesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public Builder addAllColumnValues(
          java.lang.Iterable<? extends com._42six.amino.common.bigtable.MutationProto.ColumnValue> values) {
        if (columnValuesBuilder_ == null) {
          ensureColumnValuesIsMutable();
          super.addAll(values, columnValues_);
          onChanged();
        } else {
          columnValuesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public Builder clearColumnValues() {
        if (columnValuesBuilder_ == null) {
          columnValues_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          columnValuesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public Builder removeColumnValues(int index) {
        if (columnValuesBuilder_ == null) {
          ensureColumnValuesIsMutable();
          columnValues_.remove(index);
          onChanged();
        } else {
          columnValuesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder getColumnValuesBuilder(
          int index) {
        return getColumnValuesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder getColumnValuesOrBuilder(
          int index) {
        if (columnValuesBuilder_ == null) {
          return columnValues_.get(index);  } else {
          return columnValuesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public java.util.List<? extends com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder> 
           getColumnValuesOrBuilderList() {
        if (columnValuesBuilder_ != null) {
          return columnValuesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(columnValues_);
        }
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder addColumnValuesBuilder() {
        return getColumnValuesFieldBuilder().addBuilder(
            com._42six.amino.common.bigtable.MutationProto.ColumnValue.getDefaultInstance());
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder addColumnValuesBuilder(
          int index) {
        return getColumnValuesFieldBuilder().addBuilder(
            index, com._42six.amino.common.bigtable.MutationProto.ColumnValue.getDefaultInstance());
      }
      /**
       * <code>repeated .com._42six.amino.common.bigtable.ColumnValue columnValues = 2;</code>
       */
      public java.util.List<com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder> 
           getColumnValuesBuilderList() {
        return getColumnValuesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com._42six.amino.common.bigtable.MutationProto.ColumnValue, com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder, com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder> 
          getColumnValuesFieldBuilder() {
        if (columnValuesBuilder_ == null) {
          columnValuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com._42six.amino.common.bigtable.MutationProto.ColumnValue, com._42six.amino.common.bigtable.MutationProto.ColumnValue.Builder, com._42six.amino.common.bigtable.MutationProto.ColumnValueOrBuilder>(
                  columnValues_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          columnValues_ = null;
        }
        return columnValuesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com._42six.amino.common.bigtable.MutationCodec)
    }

    static {
      defaultInstance = new MutationCodec(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com._42six.amino.common.bigtable.MutationCodec)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com__42six_amino_common_bigtable_ColumnValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com__42six_amino_common_bigtable_ColumnValue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com__42six_amino_common_bigtable_MutationCodec_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com__42six_amino_common_bigtable_MutationCodec_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024Mutation_Proto.proto\022 com._42six.amino" +
      ".common.bigtable\"\215\001\n\013ColumnValue\022\025\n\rcolu" +
      "mn_family\030\001 \002(\014\022\030\n\020column_qualifier\030\002 \002(" +
      "\014\022\031\n\021column_visibility\030\003 \002(\014\022\021\n\ttimestam" +
      "p\030\004 \002(\004\022\020\n\010isDelete\030\005 \002(\010\022\r\n\005value\030\006 \001(\014" +
      "\"a\n\rMutationCodec\022\013\n\003row\030\001 \002(\014\022C\n\014column" +
      "Values\030\002 \003(\0132-.com._42six.amino.common.b" +
      "igtable.ColumnValue"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com__42six_amino_common_bigtable_ColumnValue_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com__42six_amino_common_bigtable_ColumnValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com__42six_amino_common_bigtable_ColumnValue_descriptor,
              new java.lang.String[] { "ColumnFamily", "ColumnQualifier", "ColumnVisibility", "Timestamp", "IsDelete", "Value", });
          internal_static_com__42six_amino_common_bigtable_MutationCodec_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com__42six_amino_common_bigtable_MutationCodec_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com__42six_amino_common_bigtable_MutationCodec_descriptor,
              new java.lang.String[] { "Row", "ColumnValues", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
