/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com._42six.amino.common.thrift;

import java.util.*;

public class TAddUsersRequest implements org.apache.thrift.TBase<TAddUsersRequest, TAddUsersRequest._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TAddUsersRequest");

  private static final org.apache.thrift.protocol.TField GROUP_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("groupName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField USERS_TO_ADD_FIELD_DESC = new org.apache.thrift.protocol.TField("usersToAdd", org.apache.thrift.protocol.TType.SET, (short)2);
  private static final org.apache.thrift.protocol.TField REQUESTER_FIELD_DESC = new org.apache.thrift.protocol.TField("requester", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField VISIBILITIES_FIELD_DESC = new org.apache.thrift.protocol.TField("visibilities", org.apache.thrift.protocol.TType.SET, (short)4);

  public String groupName;
  public Set<TGroupMember> usersToAdd;
  public String requester;
  public Set<String> visibilities;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GROUP_NAME((short)1, "groupName"),
    USERS_TO_ADD((short)2, "usersToAdd"),
    REQUESTER((short)3, "requester"),
    VISIBILITIES((short)4, "visibilities");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GROUP_NAME
          return GROUP_NAME;
        case 2: // USERS_TO_ADD
          return USERS_TO_ADD;
        case 3: // REQUESTER
          return REQUESTER;
        case 4: // VISIBILITIES
          return VISIBILITIES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GROUP_NAME, new org.apache.thrift.meta_data.FieldMetaData("groupName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USERS_TO_ADD, new org.apache.thrift.meta_data.FieldMetaData("usersToAdd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TGroupMember.class))));
    tmpMap.put(_Fields.REQUESTER, new org.apache.thrift.meta_data.FieldMetaData("requester", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VISIBILITIES, new org.apache.thrift.meta_data.FieldMetaData("visibilities", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TAddUsersRequest.class, metaDataMap);
  }

  public TAddUsersRequest() {
  }

  public TAddUsersRequest(
    String groupName,
    Set<TGroupMember> usersToAdd,
    String requester,
    Set<String> visibilities)
  {
    this();
    this.groupName = groupName;
    this.usersToAdd = usersToAdd;
    this.requester = requester;
    this.visibilities = visibilities;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TAddUsersRequest(TAddUsersRequest other) {
    if (other.isSetGroupName()) {
      this.groupName = other.groupName;
    }
    if (other.isSetUsersToAdd()) {
      Set<TGroupMember> __this__usersToAdd = new HashSet<TGroupMember>();
      for (TGroupMember other_element : other.usersToAdd) {
        __this__usersToAdd.add(new TGroupMember(other_element));
      }
      this.usersToAdd = __this__usersToAdd;
    }
    if (other.isSetRequester()) {
      this.requester = other.requester;
    }
    if (other.isSetVisibilities()) {
      Set<String> __this__visibilities = new HashSet<String>();
      for (String other_element : other.visibilities) {
        __this__visibilities.add(other_element);
      }
      this.visibilities = __this__visibilities;
    }
  }

  public TAddUsersRequest deepCopy() {
    return new TAddUsersRequest(this);
  }

  @Override
  public void clear() {
    this.groupName = null;
    this.usersToAdd = null;
    this.requester = null;
    this.visibilities = null;
  }

  public String getGroupName() {
    return this.groupName;
  }

  public TAddUsersRequest setGroupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

  public void unsetGroupName() {
    this.groupName = null;
  }

  /** Returns true if field groupName is set (has been assigned a value) and false otherwise */
  public boolean isSetGroupName() {
    return this.groupName != null;
  }

  public void setGroupNameIsSet(boolean value) {
    if (!value) {
      this.groupName = null;
    }
  }

  public int getUsersToAddSize() {
    return (this.usersToAdd == null) ? 0 : this.usersToAdd.size();
  }

  public java.util.Iterator<TGroupMember> getUsersToAddIterator() {
    return (this.usersToAdd == null) ? null : this.usersToAdd.iterator();
  }

  public void addToUsersToAdd(TGroupMember elem) {
    if (this.usersToAdd == null) {
      this.usersToAdd = new HashSet<TGroupMember>();
    }
    this.usersToAdd.add(elem);
  }

  public Set<TGroupMember> getUsersToAdd() {
    return this.usersToAdd;
  }

  public TAddUsersRequest setUsersToAdd(Set<TGroupMember> usersToAdd) {
    this.usersToAdd = usersToAdd;
    return this;
  }

  public void unsetUsersToAdd() {
    this.usersToAdd = null;
  }

  /** Returns true if field usersToAdd is set (has been assigned a value) and false otherwise */
  public boolean isSetUsersToAdd() {
    return this.usersToAdd != null;
  }

  public void setUsersToAddIsSet(boolean value) {
    if (!value) {
      this.usersToAdd = null;
    }
  }

  public String getRequester() {
    return this.requester;
  }

  public TAddUsersRequest setRequester(String requester) {
    this.requester = requester;
    return this;
  }

  public void unsetRequester() {
    this.requester = null;
  }

  /** Returns true if field requester is set (has been assigned a value) and false otherwise */
  public boolean isSetRequester() {
    return this.requester != null;
  }

  public void setRequesterIsSet(boolean value) {
    if (!value) {
      this.requester = null;
    }
  }

  public int getVisibilitiesSize() {
    return (this.visibilities == null) ? 0 : this.visibilities.size();
  }

  public java.util.Iterator<String> getVisibilitiesIterator() {
    return (this.visibilities == null) ? null : this.visibilities.iterator();
  }

  public void addToVisibilities(String elem) {
    if (this.visibilities == null) {
      this.visibilities = new HashSet<String>();
    }
    this.visibilities.add(elem);
  }

  public Set<String> getVisibilities() {
    return this.visibilities;
  }

  public TAddUsersRequest setVisibilities(Set<String> visibilities) {
    this.visibilities = visibilities;
    return this;
  }

  public void unsetVisibilities() {
    this.visibilities = null;
  }

  /** Returns true if field visibilities is set (has been assigned a value) and false otherwise */
  public boolean isSetVisibilities() {
    return this.visibilities != null;
  }

  public void setVisibilitiesIsSet(boolean value) {
    if (!value) {
      this.visibilities = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case GROUP_NAME:
      if (value == null) {
        unsetGroupName();
      } else {
        setGroupName((String)value);
      }
      break;

    case USERS_TO_ADD:
      if (value == null) {
        unsetUsersToAdd();
      } else {
        setUsersToAdd((Set<TGroupMember>)value);
      }
      break;

    case REQUESTER:
      if (value == null) {
        unsetRequester();
      } else {
        setRequester((String)value);
      }
      break;

    case VISIBILITIES:
      if (value == null) {
        unsetVisibilities();
      } else {
        setVisibilities((Set<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case GROUP_NAME:
      return getGroupName();

    case USERS_TO_ADD:
      return getUsersToAdd();

    case REQUESTER:
      return getRequester();

    case VISIBILITIES:
      return getVisibilities();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case GROUP_NAME:
      return isSetGroupName();
    case USERS_TO_ADD:
      return isSetUsersToAdd();
    case REQUESTER:
      return isSetRequester();
    case VISIBILITIES:
      return isSetVisibilities();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TAddUsersRequest)
      return this.equals((TAddUsersRequest)that);
    return false;
  }

  public boolean equals(TAddUsersRequest that) {
    if (that == null)
      return false;

    boolean this_present_groupName = true && this.isSetGroupName();
    boolean that_present_groupName = true && that.isSetGroupName();
    if (this_present_groupName || that_present_groupName) {
      if (!(this_present_groupName && that_present_groupName))
        return false;
      if (!this.groupName.equals(that.groupName))
        return false;
    }

    boolean this_present_usersToAdd = true && this.isSetUsersToAdd();
    boolean that_present_usersToAdd = true && that.isSetUsersToAdd();
    if (this_present_usersToAdd || that_present_usersToAdd) {
      if (!(this_present_usersToAdd && that_present_usersToAdd))
        return false;
      if (!this.usersToAdd.equals(that.usersToAdd))
        return false;
    }

    boolean this_present_requester = true && this.isSetRequester();
    boolean that_present_requester = true && that.isSetRequester();
    if (this_present_requester || that_present_requester) {
      if (!(this_present_requester && that_present_requester))
        return false;
      if (!this.requester.equals(that.requester))
        return false;
    }

    boolean this_present_visibilities = true && this.isSetVisibilities();
    boolean that_present_visibilities = true && that.isSetVisibilities();
    if (this_present_visibilities || that_present_visibilities) {
      if (!(this_present_visibilities && that_present_visibilities))
        return false;
      if (!this.visibilities.equals(that.visibilities))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TAddUsersRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TAddUsersRequest typedOther = (TAddUsersRequest)other;

    lastComparison = Boolean.valueOf(isSetGroupName()).compareTo(typedOther.isSetGroupName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGroupName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.groupName, typedOther.groupName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsersToAdd()).compareTo(typedOther.isSetUsersToAdd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsersToAdd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usersToAdd, typedOther.usersToAdd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRequester()).compareTo(typedOther.isSetRequester());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequester()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requester, typedOther.requester);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVisibilities()).compareTo(typedOther.isSetVisibilities());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVisibilities()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.visibilities, typedOther.visibilities);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // GROUP_NAME
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.groupName = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // USERS_TO_ADD
          if (field.type == org.apache.thrift.protocol.TType.SET) {
            {
              org.apache.thrift.protocol.TSet _set12 = iprot.readSetBegin();
              this.usersToAdd = new HashSet<TGroupMember>(2*_set12.size);
              for (int _i13 = 0; _i13 < _set12.size; ++_i13)
              {
                TGroupMember _elem14;
                _elem14 = new TGroupMember();
                _elem14.read(iprot);
                this.usersToAdd.add(_elem14);
              }
              iprot.readSetEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // REQUESTER
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.requester = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // VISIBILITIES
          if (field.type == org.apache.thrift.protocol.TType.SET) {
            {
              org.apache.thrift.protocol.TSet _set15 = iprot.readSetBegin();
              this.visibilities = new HashSet<String>(2*_set15.size);
              for (int _i16 = 0; _i16 < _set15.size; ++_i16)
              {
                String _elem17;
                _elem17 = iprot.readString();
                this.visibilities.add(_elem17);
              }
              iprot.readSetEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.groupName != null) {
      oprot.writeFieldBegin(GROUP_NAME_FIELD_DESC);
      oprot.writeString(this.groupName);
      oprot.writeFieldEnd();
    }
    if (this.usersToAdd != null) {
      oprot.writeFieldBegin(USERS_TO_ADD_FIELD_DESC);
      {
        oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, this.usersToAdd.size()));
        for (TGroupMember _iter18 : this.usersToAdd)
        {
          _iter18.write(oprot);
        }
        oprot.writeSetEnd();
      }
      oprot.writeFieldEnd();
    }
    if (this.requester != null) {
      oprot.writeFieldBegin(REQUESTER_FIELD_DESC);
      oprot.writeString(this.requester);
      oprot.writeFieldEnd();
    }
    if (this.visibilities != null) {
      oprot.writeFieldBegin(VISIBILITIES_FIELD_DESC);
      {
        oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, this.visibilities.size()));
        for (String _iter19 : this.visibilities)
        {
          oprot.writeString(_iter19);
        }
        oprot.writeSetEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TAddUsersRequest(");
    boolean first = true;

    sb.append("groupName:");
    if (this.groupName == null) {
      sb.append("null");
    } else {
      sb.append(this.groupName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usersToAdd:");
    if (this.usersToAdd == null) {
      sb.append("null");
    } else {
      sb.append(this.usersToAdd);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("requester:");
    if (this.requester == null) {
      sb.append("null");
    } else {
      sb.append(this.requester);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("visibilities:");
    if (this.visibilities == null) {
      sb.append("null");
    } else {
      sb.append(this.visibilities);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

