/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com._42six.amino.common.thrift;


public enum TGroupRole implements org.apache.thrift.TEnum {
  ADMIN(0),
  CONTRIBUTOR(1),
  VIEWER(2);

  private final int value;

  private TGroupRole(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TGroupRole findByValue(int value) { 
    switch (value) {
      case 0:
        return ADMIN;
      case 1:
        return CONTRIBUTOR;
      case 2:
        return VIEWER;
      default:
        return null;
    }
  }
}
